<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>4ee498a8-4d0d-41c6-b68f-914f50427509</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../INRFS.Financer.Application/INRFS.Financer.Application.csproj" />
    <ProjectReference Include="../INRFS.Financer.Infrastructure/INRFS.Financer.Infrastructure.csproj" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>
</Project>
